###################################
## General Settings

## These settings are standard Jekyll Settings, check the Jekyll docs for help

## Preprocessor settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

## Jekyll Serve
port: 4000

## Output
siteurl:                    ## Optional
baseurl:                    ## Optional
destination: _site          ## Output folder


###################################
## Style Guide Shell Settings

## These settings are used in when generating the style guide shell
sg_title: Mirador 3 Style Guide
sg_version: 0.1
sg_keywords: miardor, jekyll, style guide, playbook, design, code
sg_author: Gary Geisler
sg_description: This Mirador 3 Style Guide is intended to document styles and processes related to the design and development of Mirador 3.
sg_language: en
sg_styles: /styleguide/css/styleguide.css
sg_favicon: /styleguide/branding/favicon.ico
# sg_ga: UA-19247091-8      ## Analytics Tracking

## Generates Style Guide Shell Styles
## Enable to change the style guide shell stylesheet.
sass:
 sass_dir: styleguide/_scss
 style: :uncompressed


###################################
## Collection Settings

## Outputs the _docs collection !Required
collections:
  docs:
    output: true

## Sets the default attributes for the Documentation and Pattern Files !Required
defaults:
  -
    scope:
      path: "_docs"
    values:
      layout: doc
      type: doc
  -
    scope:
      path: "_docs/about"
    values:
      layout: doc
      type: about
  -
    scope:
      path: "_docs/foundations"
    values:
      layout: doc
      type: foundation
  -
    scope:
      path: "_docs/components"
    values:
      layout: doc
      type: component
  -
    scope:
      path: "_docs/templates"
    values:
      layout: doc
      type: template
  -
    scope:
      path: "_docs/sample-pages"
    values:
      layout: doc
      type: sample
  -
    scope:
      path: "src/patterns"
    values:
      layout: pattern
      type: pattern
      maturity: planned
      title: Not Assigned
      styles: Not Assigned
  -
    scope:
      path: "src/patterns/sample-pages"
    values:
      type: sample
      title: Not Assigned

###################################
## Pattern Settings
## These attributes are applied to all patterns via the pattern.html layout.

pattern_author: AUTHOR NAME             ## used in <head> tag
pattern_description: DESCRIPTION        ## used in <head> tag
pattern_language: en                    ## used in <html> tag
pattern_favicon: /src/assets/images/icon.ico
pattern_styles:                 ## add style locations here
  - /src/assets/css/style.css
pattern_scripts:                ## add script locations here
  - /src/assets/js/libs/jquery-2.1.4.min.js


## Generates Pattern Styles
## Disable to prevent pattern styles from being generated.
# sass:
#   sass_dir: src/assets/_scss
#   style: :compressed
